### ISSUE TITLE
Delivery cost not being calculated on cart page

### ISSUE THREAD

**Issue by knair97** [aglipanci/woocommerce-postmates#1]
I am able to set a flat rate for the Postmates shipping method but not able to get the calculated cost to work using the quote from Postmates. I see that you have a function to do this in your code but it does not seem to work on my website. Any tips will be appreciated.

**Comment by knair97** [comment]
Sorry, I was able to find my mistake. It seems the address was not getting received properly.

**Comment by aglipanci** [comment]
@knair97 you need to enable logging and/or debugging in order to understand what is your issue. To view the logs go here https://docs.woocommerce.com/document/finding-php-error-logs/

**Comment by knair97** [comment]
Thanks! It was an issue on my end. Thank you so much for your work on this plugin :)

**Comment by aglipanci** [comment]
@knair97 I would appreciate a good review on the plugin directory so other people can start using it too. Here is the URL https://wordpress.org/plugins/woo-postmates-integration/#reviews

Cheers!
